// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Rockset
{
    /// <summary>
    /// Manages a Rockset Query Lambda.
    /// </summary>
    [RocksetResourceType("rockset:index/queryLambda:QueryLambda")]
    public partial class QueryLambda : global::Pulumi.CustomResource
    {
        /// <summary>
        /// Text describing the query lambda.
        /// </summary>
        [Output("description")]
        public Output<string?> Description { get; private set; } = null!;

        /// <summary>
        /// Unique identifier for the query lambda. Can contain alphanumeric or dash characters.
        /// </summary>
        [Output("name")]
        public Output<string> Name { get; private set; } = null!;

        [Output("sqls")]
        public Output<ImmutableArray<Outputs.QueryLambdaSql>> Sqls { get; private set; } = null!;

        /// <summary>
        /// The latest state of this query lambda.
        /// </summary>
        [Output("state")]
        public Output<string> State { get; private set; } = null!;

        /// <summary>
        /// The latest version string of this query lambda.
        /// </summary>
        [Output("version")]
        public Output<string> Version { get; private set; } = null!;

        /// <summary>
        /// The name of the workspace.
        /// </summary>
        [Output("workspace")]
        public Output<string> Workspace { get; private set; } = null!;


        /// <summary>
        /// Create a QueryLambda resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public QueryLambda(string name, QueryLambdaArgs args, CustomResourceOptions? options = null)
            : base("rockset:index/queryLambda:QueryLambda", name, args ?? new QueryLambdaArgs(), MakeResourceOptions(options, ""))
        {
        }

        private QueryLambda(string name, Input<string> id, QueryLambdaState? state = null, CustomResourceOptions? options = null)
            : base("rockset:index/queryLambda:QueryLambda", name, state, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing QueryLambda resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="state">Any extra arguments used during the lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static QueryLambda Get(string name, Input<string> id, QueryLambdaState? state = null, CustomResourceOptions? options = null)
        {
            return new QueryLambda(name, id, state, options);
        }
    }

    public sealed class QueryLambdaArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Text describing the query lambda.
        /// </summary>
        [Input("description")]
        public Input<string>? Description { get; set; }

        /// <summary>
        /// Unique identifier for the query lambda. Can contain alphanumeric or dash characters.
        /// </summary>
        [Input("name")]
        public Input<string>? Name { get; set; }

        [Input("sqls", required: true)]
        private InputList<Inputs.QueryLambdaSqlArgs>? _sqls;
        public InputList<Inputs.QueryLambdaSqlArgs> Sqls
        {
            get => _sqls ?? (_sqls = new InputList<Inputs.QueryLambdaSqlArgs>());
            set => _sqls = value;
        }

        /// <summary>
        /// The name of the workspace.
        /// </summary>
        [Input("workspace", required: true)]
        public Input<string> Workspace { get; set; } = null!;

        public QueryLambdaArgs()
        {
        }
        public static new QueryLambdaArgs Empty => new QueryLambdaArgs();
    }

    public sealed class QueryLambdaState : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Text describing the query lambda.
        /// </summary>
        [Input("description")]
        public Input<string>? Description { get; set; }

        /// <summary>
        /// Unique identifier for the query lambda. Can contain alphanumeric or dash characters.
        /// </summary>
        [Input("name")]
        public Input<string>? Name { get; set; }

        [Input("sqls")]
        private InputList<Inputs.QueryLambdaSqlGetArgs>? _sqls;
        public InputList<Inputs.QueryLambdaSqlGetArgs> Sqls
        {
            get => _sqls ?? (_sqls = new InputList<Inputs.QueryLambdaSqlGetArgs>());
            set => _sqls = value;
        }

        /// <summary>
        /// The latest state of this query lambda.
        /// </summary>
        [Input("state")]
        public Input<string>? State { get; set; }

        /// <summary>
        /// The latest version string of this query lambda.
        /// </summary>
        [Input("version")]
        public Input<string>? Version { get; set; }

        /// <summary>
        /// The name of the workspace.
        /// </summary>
        [Input("workspace")]
        public Input<string>? Workspace { get; set; }

        public QueryLambdaState()
        {
        }
        public static new QueryLambdaState Empty => new QueryLambdaState();
    }
}
