// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Rockset.Outputs
{

    [OutputType]
    public sealed class GcsCollectionSourceXml
    {
        /// <summary>
        /// Tag to differentiate between attributes and elements.
        /// </summary>
        public readonly string? AttributePrefix;
        /// <summary>
        /// Tags with which documents are identified
        /// </summary>
        public readonly string? DocTag;
        /// <summary>
        /// Can be one of: UTF-8, ISO*8859*1, UTF-16.
        /// </summary>
        public readonly string? Encoding;
        /// <summary>
        /// Tag until which xml is ignored.
        /// </summary>
        public readonly string? RootTag;
        /// <summary>
        /// Tag used for the value when there are attributes in the element having no child.
        /// </summary>
        public readonly string? ValueTag;

        [OutputConstructor]
        private GcsCollectionSourceXml(
            string? attributePrefix,

            string? docTag,

            string? encoding,

            string? rootTag,

            string? valueTag)
        {
            AttributePrefix = attributePrefix;
            DocTag = docTag;
            Encoding = encoding;
            RootTag = rootTag;
            ValueTag = valueTag;
        }
    }
}
