// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Rockset.Outputs
{

    [OutputType]
    public sealed class KafkaCollectionSourceStatus
    {
        /// <summary>
        /// Number of documents processed by this Kafka topic.
        /// </summary>
        public readonly int? DocumentsProcessed;
        /// <summary>
        /// The type of partitions on a field.
        /// </summary>
        public readonly string? LastConsumedTime;
        /// <summary>
        /// The status info per partition.
        /// </summary>
        public readonly ImmutableArray<Outputs.KafkaCollectionSourceStatusPartition> Partitions;
        /// <summary>
        /// State of the Kafka source. Possible values: NO_DOCS_YET, ACTIVE, DORMANT.
        /// </summary>
        public readonly string? State;

        [OutputConstructor]
        private KafkaCollectionSourceStatus(
            int? documentsProcessed,

            string? lastConsumedTime,

            ImmutableArray<Outputs.KafkaCollectionSourceStatusPartition> partitions,

            string? state)
        {
            DocumentsProcessed = documentsProcessed;
            LastConsumedTime = lastConsumedTime;
            Partitions = partitions;
            State = state;
        }
    }
}
