// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Rockset.Outputs
{

    [OutputType]
    public sealed class KafkaCollectionSourceStatusPartition
    {
        /// <summary>
        /// Per partition lag for offset.
        /// </summary>
        public readonly int? OffsetLag;
        /// <summary>
        /// The number of this partition.
        /// </summary>
        public readonly int? PartitionNumber;
        /// <summary>
        /// Latest offset of this partition.
        /// </summary>
        public readonly int? PartitionOffset;

        [OutputConstructor]
        private KafkaCollectionSourceStatusPartition(
            int? offsetLag,

            int? partitionNumber,

            int? partitionOffset)
        {
            OffsetLag = offsetLag;
            PartitionNumber = partitionNumber;
            PartitionOffset = partitionOffset;
        }
    }
}
