// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package rockset

import (
	"context"
	"reflect"

	"errors"
	"github.com/ddn0/pulumi-rockset/sdk/go/rockset/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// Manages a Rockset User.
//
// First and last name can only be managed for users who have accepted the invite,
// i.e. when the state is ACCEPTED.
type User struct {
	pulumi.CustomResourceState

	// The ISO-8601 time of when the user was created.
	CreatedAt pulumi.StringOutput `pulumi:"createdAt"`
	// Email address of the user. Also used to identify the user.
	Email pulumi.StringOutput `pulumi:"email"`
	// User's first name. This can only be set once the state is ACTIVE, i.e after the user has accepted the invite.
	FirstName pulumi.StringPtrOutput `pulumi:"firstName"`
	// User's last name. This can only be set once the state is ACTIVE, i.e after the user has accepted the invite.
	LastName pulumi.StringPtrOutput `pulumi:"lastName"`
	// List of roles for the user. E.g. 'admin', 'member', 'read-only'.
	Roles pulumi.StringArrayOutput `pulumi:"roles"`
	// State of the user, either NEW or ACTIVE.
	State pulumi.StringOutput `pulumi:"state"`
}

// NewUser registers a new resource with the given unique name, arguments, and options.
func NewUser(ctx *pulumi.Context,
	name string, args *UserArgs, opts ...pulumi.ResourceOption) (*User, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.Email == nil {
		return nil, errors.New("invalid value for required argument 'Email'")
	}
	if args.Roles == nil {
		return nil, errors.New("invalid value for required argument 'Roles'")
	}
	opts = internal.PkgResourceDefaultOpts(opts)
	var resource User
	err := ctx.RegisterResource("rockset:index/user:User", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetUser gets an existing User resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetUser(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *UserState, opts ...pulumi.ResourceOption) (*User, error) {
	var resource User
	err := ctx.ReadResource("rockset:index/user:User", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering User resources.
type userState struct {
	// The ISO-8601 time of when the user was created.
	CreatedAt *string `pulumi:"createdAt"`
	// Email address of the user. Also used to identify the user.
	Email *string `pulumi:"email"`
	// User's first name. This can only be set once the state is ACTIVE, i.e after the user has accepted the invite.
	FirstName *string `pulumi:"firstName"`
	// User's last name. This can only be set once the state is ACTIVE, i.e after the user has accepted the invite.
	LastName *string `pulumi:"lastName"`
	// List of roles for the user. E.g. 'admin', 'member', 'read-only'.
	Roles []string `pulumi:"roles"`
	// State of the user, either NEW or ACTIVE.
	State *string `pulumi:"state"`
}

type UserState struct {
	// The ISO-8601 time of when the user was created.
	CreatedAt pulumi.StringPtrInput
	// Email address of the user. Also used to identify the user.
	Email pulumi.StringPtrInput
	// User's first name. This can only be set once the state is ACTIVE, i.e after the user has accepted the invite.
	FirstName pulumi.StringPtrInput
	// User's last name. This can only be set once the state is ACTIVE, i.e after the user has accepted the invite.
	LastName pulumi.StringPtrInput
	// List of roles for the user. E.g. 'admin', 'member', 'read-only'.
	Roles pulumi.StringArrayInput
	// State of the user, either NEW or ACTIVE.
	State pulumi.StringPtrInput
}

func (UserState) ElementType() reflect.Type {
	return reflect.TypeOf((*userState)(nil)).Elem()
}

type userArgs struct {
	// Email address of the user. Also used to identify the user.
	Email string `pulumi:"email"`
	// User's first name. This can only be set once the state is ACTIVE, i.e after the user has accepted the invite.
	FirstName *string `pulumi:"firstName"`
	// User's last name. This can only be set once the state is ACTIVE, i.e after the user has accepted the invite.
	LastName *string `pulumi:"lastName"`
	// List of roles for the user. E.g. 'admin', 'member', 'read-only'.
	Roles []string `pulumi:"roles"`
}

// The set of arguments for constructing a User resource.
type UserArgs struct {
	// Email address of the user. Also used to identify the user.
	Email pulumi.StringInput
	// User's first name. This can only be set once the state is ACTIVE, i.e after the user has accepted the invite.
	FirstName pulumi.StringPtrInput
	// User's last name. This can only be set once the state is ACTIVE, i.e after the user has accepted the invite.
	LastName pulumi.StringPtrInput
	// List of roles for the user. E.g. 'admin', 'member', 'read-only'.
	Roles pulumi.StringArrayInput
}

func (UserArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*userArgs)(nil)).Elem()
}

type UserInput interface {
	pulumi.Input

	ToUserOutput() UserOutput
	ToUserOutputWithContext(ctx context.Context) UserOutput
}

func (*User) ElementType() reflect.Type {
	return reflect.TypeOf((**User)(nil)).Elem()
}

func (i *User) ToUserOutput() UserOutput {
	return i.ToUserOutputWithContext(context.Background())
}

func (i *User) ToUserOutputWithContext(ctx context.Context) UserOutput {
	return pulumi.ToOutputWithContext(ctx, i).(UserOutput)
}

// UserArrayInput is an input type that accepts UserArray and UserArrayOutput values.
// You can construct a concrete instance of `UserArrayInput` via:
//
//	UserArray{ UserArgs{...} }
type UserArrayInput interface {
	pulumi.Input

	ToUserArrayOutput() UserArrayOutput
	ToUserArrayOutputWithContext(context.Context) UserArrayOutput
}

type UserArray []UserInput

func (UserArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*User)(nil)).Elem()
}

func (i UserArray) ToUserArrayOutput() UserArrayOutput {
	return i.ToUserArrayOutputWithContext(context.Background())
}

func (i UserArray) ToUserArrayOutputWithContext(ctx context.Context) UserArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(UserArrayOutput)
}

// UserMapInput is an input type that accepts UserMap and UserMapOutput values.
// You can construct a concrete instance of `UserMapInput` via:
//
//	UserMap{ "key": UserArgs{...} }
type UserMapInput interface {
	pulumi.Input

	ToUserMapOutput() UserMapOutput
	ToUserMapOutputWithContext(context.Context) UserMapOutput
}

type UserMap map[string]UserInput

func (UserMap) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*User)(nil)).Elem()
}

func (i UserMap) ToUserMapOutput() UserMapOutput {
	return i.ToUserMapOutputWithContext(context.Background())
}

func (i UserMap) ToUserMapOutputWithContext(ctx context.Context) UserMapOutput {
	return pulumi.ToOutputWithContext(ctx, i).(UserMapOutput)
}

type UserOutput struct{ *pulumi.OutputState }

func (UserOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**User)(nil)).Elem()
}

func (o UserOutput) ToUserOutput() UserOutput {
	return o
}

func (o UserOutput) ToUserOutputWithContext(ctx context.Context) UserOutput {
	return o
}

// The ISO-8601 time of when the user was created.
func (o UserOutput) CreatedAt() pulumi.StringOutput {
	return o.ApplyT(func(v *User) pulumi.StringOutput { return v.CreatedAt }).(pulumi.StringOutput)
}

// Email address of the user. Also used to identify the user.
func (o UserOutput) Email() pulumi.StringOutput {
	return o.ApplyT(func(v *User) pulumi.StringOutput { return v.Email }).(pulumi.StringOutput)
}

// User's first name. This can only be set once the state is ACTIVE, i.e after the user has accepted the invite.
func (o UserOutput) FirstName() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *User) pulumi.StringPtrOutput { return v.FirstName }).(pulumi.StringPtrOutput)
}

// User's last name. This can only be set once the state is ACTIVE, i.e after the user has accepted the invite.
func (o UserOutput) LastName() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *User) pulumi.StringPtrOutput { return v.LastName }).(pulumi.StringPtrOutput)
}

// List of roles for the user. E.g. 'admin', 'member', 'read-only'.
func (o UserOutput) Roles() pulumi.StringArrayOutput {
	return o.ApplyT(func(v *User) pulumi.StringArrayOutput { return v.Roles }).(pulumi.StringArrayOutput)
}

// State of the user, either NEW or ACTIVE.
func (o UserOutput) State() pulumi.StringOutput {
	return o.ApplyT(func(v *User) pulumi.StringOutput { return v.State }).(pulumi.StringOutput)
}

type UserArrayOutput struct{ *pulumi.OutputState }

func (UserArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*User)(nil)).Elem()
}

func (o UserArrayOutput) ToUserArrayOutput() UserArrayOutput {
	return o
}

func (o UserArrayOutput) ToUserArrayOutputWithContext(ctx context.Context) UserArrayOutput {
	return o
}

func (o UserArrayOutput) Index(i pulumi.IntInput) UserOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) *User {
		return vs[0].([]*User)[vs[1].(int)]
	}).(UserOutput)
}

type UserMapOutput struct{ *pulumi.OutputState }

func (UserMapOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*User)(nil)).Elem()
}

func (o UserMapOutput) ToUserMapOutput() UserMapOutput {
	return o
}

func (o UserMapOutput) ToUserMapOutputWithContext(ctx context.Context) UserMapOutput {
	return o
}

func (o UserMapOutput) MapIndex(k pulumi.StringInput) UserOutput {
	return pulumi.All(o, k).ApplyT(func(vs []interface{}) *User {
		return vs[0].(map[string]*User)[vs[1].(string)]
	}).(UserOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*UserInput)(nil)).Elem(), &User{})
	pulumi.RegisterInputType(reflect.TypeOf((*UserArrayInput)(nil)).Elem(), UserArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*UserMapInput)(nil)).Elem(), UserMap{})
	pulumi.RegisterOutputType(UserOutput{})
	pulumi.RegisterOutputType(UserArrayOutput{})
	pulumi.RegisterOutputType(UserMapOutput{})
}
