// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Rockset.Inputs
{

    public sealed class KafkaCollectionSourceStatusPartitionArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Per partition lag for offset.
        /// </summary>
        [Input("offsetLag")]
        public Input<int>? OffsetLag { get; set; }

        /// <summary>
        /// The number of this partition.
        /// </summary>
        [Input("partitionNumber")]
        public Input<int>? PartitionNumber { get; set; }

        /// <summary>
        /// Latest offset of this partition.
        /// </summary>
        [Input("partitionOffset")]
        public Input<int>? PartitionOffset { get; set; }

        public KafkaCollectionSourceStatusPartitionArgs()
        {
        }
        public static new KafkaCollectionSourceStatusPartitionArgs Empty => new KafkaCollectionSourceStatusPartitionArgs();
    }
}
