// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

/**
 * Manages a Rockset GCS Integration.
 */
export class GcsIntegration extends pulumi.CustomResource {
    /**
     * Get an existing GcsIntegration resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: GcsIntegrationState, opts?: pulumi.CustomResourceOptions): GcsIntegration {
        return new GcsIntegration(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'rockset:index/gcsIntegration:GcsIntegration';

    /**
     * Returns true if the given object is an instance of GcsIntegration.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is GcsIntegration {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === GcsIntegration.__pulumiType;
    }

    /**
     * Text describing the integration.
     */
    public readonly description!: pulumi.Output<string | undefined>;
    /**
     * Unique identifier for the integration. Can contain alphanumeric or dash characters.
     */
    public readonly name!: pulumi.Output<string>;
    /**
     * The GCP service account key JSON.
     */
    public readonly serviceAccountKey!: pulumi.Output<string>;

    /**
     * Create a GcsIntegration resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: GcsIntegrationArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: GcsIntegrationArgs | GcsIntegrationState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as GcsIntegrationState | undefined;
            resourceInputs["description"] = state ? state.description : undefined;
            resourceInputs["name"] = state ? state.name : undefined;
            resourceInputs["serviceAccountKey"] = state ? state.serviceAccountKey : undefined;
        } else {
            const args = argsOrState as GcsIntegrationArgs | undefined;
            if ((!args || args.serviceAccountKey === undefined) && !opts.urn) {
                throw new Error("Missing required property 'serviceAccountKey'");
            }
            resourceInputs["description"] = args ? args.description : undefined;
            resourceInputs["name"] = args ? args.name : undefined;
            resourceInputs["serviceAccountKey"] = args ? args.serviceAccountKey : undefined;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(GcsIntegration.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering GcsIntegration resources.
 */
export interface GcsIntegrationState {
    /**
     * Text describing the integration.
     */
    description?: pulumi.Input<string>;
    /**
     * Unique identifier for the integration. Can contain alphanumeric or dash characters.
     */
    name?: pulumi.Input<string>;
    /**
     * The GCP service account key JSON.
     */
    serviceAccountKey?: pulumi.Input<string>;
}

/**
 * The set of arguments for constructing a GcsIntegration resource.
 */
export interface GcsIntegrationArgs {
    /**
     * Text describing the integration.
     */
    description?: pulumi.Input<string>;
    /**
     * Unique identifier for the integration. Can contain alphanumeric or dash characters.
     */
    name?: pulumi.Input<string>;
    /**
     * The GCP service account key JSON.
     */
    serviceAccountKey: pulumi.Input<string>;
}
